<?php

// http://www.lsis.org/elmouelhia/sf/coursSymfonyDQL.pdf

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    public function findNearSites($lat, $lon, $date, $radius = 100)
    {
        //TODO date=>sqldate
        $sqldate = date('Y-m-d', strtotime($date));
        //$sqldate = '2017-11-25';

        // Pour tester  app/console doctrine:query:dql "requeteDQL"
        // https://github.com/beberlei/DoctrineExtensions

        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT s.siteid,s.sitenom,s.longitude,s.latitude,s.type,s.ville,s.adresse,
						count(sor.idsortie) as nsorties,
						round((6371 * acos(cos(radians(:lat)) * cos(radians(s.latitude)) * cos(radians(s.longitude) - radians(:lon)) + sin(radians(:lat)) * sin(radians(s.latitude)))), 1) AS distance 
						FROM AppBundle:Site s 
						LEFT JOIN AppBundle:Sortie sor 
								WITH sor.ssite=s.siteid AND sor.date like :sqldate
						GROUP BY s.siteid
						HAVING distance <= :radius
						ORDER by nsorties DESC,distance
						')
                ->setMaxResults(100)
                ->setParameter('lat', $lat)
                ->setParameter('lon', $lon)
                ->setParameter('radius', $radius)
                ->setParameter('sqldate', $sqldate.' %');

        // TODO : LIMIT 100 ?

        return $query->getResult();

        /*
        $select = "SELECT siteid,sitenom,longitude,latitude,type,
          count(idsortie) as nsorties,
          round( ( 6371 * acos( cos( radians(:lat) ) * cos( radians( site.latitude ) )
                * cos( radians(site.longitude) - radians(:lon)) + sin(radians(:lat))
                * sin( radians(site.latitude)))), 1) AS distance
          FROM site
          LEFT JOIN sortie on ssite=siteid and sortie.date like '". $sqldate." %'
          GROUP by siteid
          ORDER by nsorties DESC,distance
          LIMIT 100";
        */
    }
}
