<?php

namespace AppBundle\Repository;

/**
 * SuivisortieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuivisortieRepository extends \Doctrine\ORM\EntityRepository
{
}
